### ISSUE TITLE
如果 isTarget 不是Bean 而是 List<Bean> 如何判断呢？

### ISSUE THREAD

**Issue by spysoos** [xiaopansky/AssemblyAdapter#1]
如果 isTarget 不是Bean 而是 List<Bean> 如何判断呢？

**Comment by panpf** [comment]
直接 instanceof List

**Comment by spysoos** [comment]
也行吧，就是没能准确判断List<Bean> 中Bean的类型，有点小限制

**Comment by panpf** [comment]
这就属于Java泛型的判断问题了，基本上没有比较好的办法能直接取到泛型的类型。有个小技巧就是你取出列表中第一个元素去判断它的类型，但这个方法对于Object类型的就无能为力了
