### ISSUE TITLE
减少实现的方法数

### ISSUE THREAD

**Issue by wenjiahui** [xiaopansky/AssemblyAdapter#2]
将AssemblyItem等类的 onFindViews()， onConfigViews(Context var1)改为默认实现，不需要在子类强制实现。子类按需重写。另外findViewById(int id)方法改为泛型自动转换类型。

**Comment by panpf** [comment]
感谢你的关注！

先说第一个问题之所以区分出这几个方法是为了强制规范代码书写，我想你也见过把findView和配置view的代码混在一起的，代码量少的情况下还好，一旦多了就不想读了。另外通过我们自己的使用情况来看大部分item的代码量都是很大的，因此区分是很有必要的，如果你实在感觉不爽你可以继承assemblyitem改一下。

第二个问题可以考虑加上但不会很快。

再次谢谢你的关注，祝你工作愉快！

**Comment by wenjiahui** [comment]
谢谢你的回复，目前项目使用butterknife绑定view和监听器，因此觉得这两个方法有点多余，我继承assemblyitem改一下。这项目很棒。
