### ISSUE TITLE
是来赞的

### ISSUE THREAD

**Issue by feer921** [xiaopansky/AssemblyAdapter#4]
开一条issue，就是想说，可组装化这思路真是不错！！

不过对于点击事件还有优化的空间，可以往这方面优化一下，个人建议，不需要点击事件放在Item里，不考虑长按情况的话点击事件无非就两种：1、整个列表而言单个item的点击事件；2、每个Item中Child View的点击事件；放眼Activity来看，如果把点击事件放在你现在的Demo中示例的AssemblyItemFactory的子类，势必会造成Activity需要实现多个接口来完成点击后的逻辑，建议为：对于点击事件的接口，可以定义为通用且统一接口，置于最高级别的基类AssemblyAdapter或者AssemblyItem, 另:这两种基类还需要进一步往通用化的功能完善。

**Comment by panpf** [comment]
多谢赞赏，我会认真考虑你的建议的，也欢迎你提交 Pull request
