### ISSUE TITLE
很不错，先感谢一下作者的贡献

### ISSUE THREAD

**Issue by ele-admin** [xiaopansky/AssemblyAdapter#5]
首先很多的Adapter开源项目的封装太臃肿了，很多功能是多余的，就比如说下拉刷新的功能，我觉得这个完全是多余的功能，下拉刷新为什么要封装到适配器里面，用自带的SwipeRefreshLayout就挺好的，还有很多开源的下拉刷新的库，Adapter里面有一个加载更多的功能就非常好了，希望作者不要加入下拉刷新的功能，还有多布局的功能，其实RecyclerView本身的多布局的实现就不是很复杂，只需要重写一个getItemViewType方法即可，希望对多布局这一块也能够保持原生的实现步骤，如果对原生的一些方法改造幅度过大，对开发人员来说并不是一件好事

**Comment by panpf** [comment]
我这就是基于原生 getItemViewType 的扩展，只是用法更方便了一些，可以方便的组装使用，而不用改 Adapter。

原生只提供了基础的实现是有它的考虑的，它要满足所有的使用场景，就没法做更上层的封装，牺牲了写法效率

assembly adapter 是 adapter 的进阶用法，初级开发人员在基础 adapter 都没用过或者没弄懂的情况下不建议使用

另外 assembly adapter 也并不能满足所有的使用场景，针对适合的场景使用就行，万事不必强求
