### ISSUE TITLE
RecyclerView 水平滑动带Loadmore只执行了一次Loamore

### ISSUE THREAD

**Issue by spysoos** [xiaopansky/AssemblyAdapter#7]
RecyclerView 水平滑动带Loadmore只执行了一次Loamore

**Comment by spysoos** [comment]
作者有联系方式吗？ 我是这个库的重度使用者，希望能得到你的帮助

**Comment by spysoos** [comment]
错了，不是只加载一次，是我的loadmore占满全屏后，被添加的内容跑到loadmore的前面去了

**Comment by panpf** [comment]
🤝
