### ISSUE TITLE
很酷，有个小问题：加载更多有些不自然

### ISSUE THREAD

**Issue by spysoos** [xiaopansky/AssemblyAdapter#9]
加载更多有些不自然：加载更多得到增加的数据后，刷新数据会导致原先的最后一项消失然后又重新添加到列表内。另外，新增加的内容添加后列表也会向下滑动，希望能改进

**Comment by panpf** [comment]
你说的这个问题，要结合你使用的 View 来研究怎么解决，更多的是在 View 方面，因为 AssemblyAdapter 只负责提供数据，对于数据的变化 View 怎么刷新页面就不是 Adapter 层面能控制的了，推荐你使用 RecyclerView 加 AssemblyPagedListAdapter 可以有比较好的效果
